// API ENDPOINTS — single source of truth for all /api/* paths
export const ENDPOINTS = {
  AUTH: {
    ME:              '/api/auth/me',
    LOGIN:           '/api/auth/login',
    SIGNUP:          '/api/auth/signup',
    LOGOUT:          '/api/auth/logout',
    VERIFY_OTP:      '/api/auth/verify-otp',
    RESEND_OTP:      '/api/auth/resend-otp',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
  },
  PROFILE: '/api/profile',
  COURSES: {
    LIST:    '/api/courses',
    BY_SLUG: (slug) => `/api/courses/${slug}`,
  },
  ENROLLMENTS: {
    CHECK: (courseId) => `/api/enrollments/check/${courseId}`,
  },
  PAYMENTS: {
    CREATE_ORDER: '/api/payments/create-order',
    VERIFY:       '/api/payments/verify',
  },
  COUPONS: {
    VALIDATE: '/api/coupons/validate',
  },
  CURRENT_AFFAIRS: {
    LIST:    '/api/current-affairs',
    BY_SLUG: (slug) => `/api/current-affairs/${slug}`,
  },
  UPLOAD: {
    PIC:   '/api/upload/pic',
    PDF:   '/api/upload/pdf',
    VIDEO: '/api/upload/video',
    IMAGE: '/api/upload/image',
  },
  STUDENT: {
    ENROLLMENTS:  '/api/student/enrollments',
    TESTS:        '/api/student/tests',
    TEST_START:   (id) => `/api/student/tests/${id}/start`,
    TEST_SUBMIT:  (id) => `/api/student/tests/${id}/submit`,
    RESULTS:      '/api/student/results',
    RESULT_BY_ID: (id) => `/api/student/results/${id}`,
    LEADERBOARD:  (testId) => `/api/student/leaderboard/${testId}`,
  },
  ADMIN: {
    USERS:               '/api/admin/users',
    USER_BY_ID:          (id) => `/api/admin/users/${id}`,
    USERS_SEARCH:        (q) => `/api/admin/users?search=${encodeURIComponent(q)}`,
    COURSES:             '/api/admin/courses',
    COURSE_BY_ID:        (id) => `/api/admin/courses/${id}`,
    COURSE_SUBJECTS:     (id) => `/api/admin/courses/${id}/subjects`,
    SUBJECT_BY_ID:       (id) => `/api/admin/subjects/${id}`,
    SUBJECT_CHAPTERS:    (id) => `/api/admin/subjects/${id}/chapters`,
    CHAPTER_BY_ID:       (id) => `/api/admin/chapters/${id}`,
    CHAPTER_CONTENT:     (id) => `/api/admin/chapters/${id}/content`,
    CONTENT_BY_ID:       (id) => `/api/admin/content/${id}`,
    TESTS:               '/api/admin/tests',
    TEST_BY_ID:          (id) => `/api/admin/tests/${id}`,
    TEST_QUESTIONS:      (id) => `/api/admin/tests/${id}/questions`,
    QUESTION_BY_ID:      (id) => `/api/admin/questions/${id}`,
    PAYMENTS:            '/api/admin/payments',
    ANALYTICS:           '/api/admin/analytics',
    CURRENT_AFFAIRS:     '/api/admin/current-affairs',
    CURRENT_AFFAIR_BY_ID:(id) => `/api/admin/current-affairs/${id}`,
    LIVE_CLASSES:        '/api/admin/live-classes',
    LIVE_CLASS_BY_ID:    (id) => `/api/admin/live-classes/${id}`,
    COUPONS:             '/api/admin/coupons',
    COUPON_BY_ID:        (id) => `/api/admin/coupons/${id}`,
    NOTICES:             '/api/admin/notices',
    NOTICE_BY_ID:        (id) => `/api/admin/notices/${id}`,
    SETTINGS:            '/api/admin/settings',
    HOMEPAGE:            '/api/admin/homepage',
  },
  HOMEPAGE: '/api/homepage',
  SETTINGS: '/api/settings',
};
