// PAGE ROUTES — single source of truth for all page href paths
export const ROUTES = {
  HOME:             '/',
  LOGIN:            '/login',
  SIGNUP:           '/signup',
  VERIFY_OTP:       '/verify-otp',
  FORGOT_PASSWORD:  '/forgot-password',
  BLOG:             '/blog',
  BLOG_POST:        (slug) => `/blog/${slug}`,
  ABOUT:            '/about',
  CONTACT:          '/contact',

  ADMIN: {
    DASHBOARD:       '/admin',
    USERS:           '/admin/users',
    COURSES:         '/admin/courses',
    COURSE:          (id) => `/admin/courses/${id}`,
    TESTS:           '/admin/tests',
    TEST_QUESTIONS:  (id) => `/admin/tests/${id}/questions`,
    PAYMENTS:        '/admin/payments',
    ANALYTICS:       '/admin/analytics',
    CURRENT_AFFAIRS: '/admin/current-affairs',
    LIVE_CLASSES:    '/admin/live-classes',
    COUPONS:         '/admin/coupons',
    NOTICES:         '/admin/notices',
    SETTINGS:        '/admin/settings',
    HOMEPAGE:        '/admin/homepage',
  },

  STUDENT: {
    DASHBOARD:       '/student',
    MY_COURSES:      '/student/my-courses',
    COURSES:         '/student/courses',
    COURSE_DETAIL:   (slug) => `/student/courses/${slug}`,
    COURSE:          (id) => `/student/my-courses/${id}`,
    TESTS:           '/student/tests',
    TEST:            (id) => `/student/tests/${id}`,
    RESULTS:         '/student/results',
    RESULT:          (id) => `/student/results/${id}`,
    LEADERBOARD:     '/student/leaderboard',
    CURRENT_AFFAIRS: '/student/current-affairs',
    LIVE_CLASSES:    '/student/live-classes',
    SCHEDULE:        '/student/schedule',
    NOTIFICATIONS:   '/student/notifications',
    PROFILE:         '/student/profile',
  },
};
